apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  ingressClassName: nginx
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: query-srv
                port:
                  number: 4002
          - path: /posts/?(.*)/comments
            pathType: ImplementationSpecific
            backend:
              service:
                name: comments-srv
                port:
                  number: 4001
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-srv
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   rules:
#     - host: posts.com
#       http:
#         paths:
#           - path: /posts/create
#             pathType: Prefix
#             backend:
#               service:
#                 name: posts-cluster-srv
#                 port:
#                   number: 4000
#           - path: /posts
#             pathType: Prefix
#             backend:
#               service:
#                 name: query-srv  # Fixed service name (was query-src)
#                 port:
#                   number: 4002
#           - path: /posts/(.*)/comments
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: comments-srv
#                 port:
#                   number: 4001
#           - path: /(.*)
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: client-srv  # Changed from event-srv to client-srv
#                 port:
#                   number: 3000               


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-srv
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: posts.com
#       http:
#         paths:
#           - path: /posts
#             pathType: Prefix
#             backend:
#               service:
#                 name: posts-clusterip-srv
#                 port:
#                   number: 4000


                  #####
                  ### ecs + :q 
                  ### ecs + :q!
                  ### esc + :wq
                  ### esc + :wq!
                   