apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: rallycoding/posts-100
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000


# apiVersion: apps/v1
# kind: Deployment
# metadata: 
#   name: posts-depl  # Changed from tickets-depl
#   # name: tickets-depl
# spec: 
#   replicas: 1
#   selector: 
#     matchLabels:
#       app: posts
#   template:
#     metadata:
#       labels: 
#         app: posts
#     spec:
#       containers:
#         - name: posts
#           image: stephengrider/posts:latest
#           env:
#             - name: EVENT_BUS_SERVICE
#               value: "event-bus-srv.default.svc.cluster.local"
# ---
# apiVersion: v1          
# kind: Service
# metadata:
#   name: posts-cluster-srv
# spec:  
#   selector:
#     app: posts
#   ports:
#     - name: posts
#       protocol: TCP
#       port: 4000
#       targetPort: 4000
      
#       # port: 4005
#       # targetPort: 4005

